version: "3.9"

services:
  db:
    image: postgres:16
    container_name: angelbot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: angelbot
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: angelbot
    volumes:
      - ./AngelBot/database/postgres-data:/var/lib/postgresql/data

  backend:
    build: ./AngelBot
    container_name: angelbot-backend
    env_file:
      - ./AngelBot/.env.prod
    environment:
      - DB_CONNECTION_STRING=Host=db;Port=5432;Database=angelbot;Username=angelbot;Password=${POSTGRES_PASSWORD}
    depends_on:
      - db
    ports:
      - "5005:5005"
    restart: unless-stopped

  frontend:
    build: ./angeldashboard
    container_name: angelbot-frontend
    env_file:
      - ./angeldashboard/.env.prod
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
