version: "3.9"

services:
  db:
    image: postgres:16
    container_name: angelbot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: angelbot
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: angelbot
    ports:
      - "5432:5432"
    volumes:
      - ./database/postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: angelbot-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@angelbot.dev
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
